##-------------------------------------------------------------------------------------------##
##                                                                                           ##
##  Color codes: & + 0 (black), 1 (dark blue), 2 (dark green), 3 (dark aqua), 4 (dark red),  ##
##               5 (dark purple), 6 (gold), 7 (gray), 8 (dark gray), 9 (blue),               ##
##               a (green), b (aqua), c (red), d (light purple), e (yellow), f (white),      ##
##               k (magic), l (bold), m (strike through), n (underline),                     ##
##               o (italic), r (reset)                                                       ##
##                                                                                           ##
##-------------------------------------------------------------------------------------------##

## Language file
language-file: en_us.yml

## Proxy (no port)
proxy: 127.0.0.1

## Tag color configuration
tags:
  member: '&7[Member]'
  vip: '&a[VIP]&r'
  mvp: '&b[MVP]&r'
  moderator: '&2[Moderator]&r'
  developer: '&c[Developer]&r'
  builder: '&9[Builder]&r'
  admin: '&c[Admin]&r'
  owner: '&4[Owner]&r'
  cdesigner: '&3[CDesigner]&r'

## Chat configuration
chat-format: '%prefix% %name%:&f %message%'
chat-filter: false

spawn:
  x: 0
  y: 80
  z: 0

## What server is this running on? (smp, story, lobby)
mode: lobby

## If the server is running on 'lobby' modify the settings here.
lobby-settings:

## If the server is running on 'smp' modify the settings here.
survival-settings:

## If the server is running on 'story' modify the settings here.
story-settings:

## Cooldowns are in seconds
command-settings:
  home:
    cooldown: 45
  random-teleport:
    bounds:
      x:
        min: -1000
        max: 1000
      z:
        min: -1000
        max: 1000
    cooldown: 300
  bug-report:
    cooldown: 240
  tpa:
    cooldown: 45

## Link to the shop
shop-link: 'https://shop.arcadiaserver.ml'